config/routes.rb
Rails.application.routes.draw do

  resources :books

  devise_for :users

  devise_for :admins, path: 'admins', skip: [:registrations]

  authenticated :user do
    root :to => 'dashboard#user_home', as: :user_root
  end

  authenticated :admin do
    root :to => 'admins/books#new', as: :admin_root
  end

  scope :admins, module: :admins, as: 'admins' do
    resources :books
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#home' 
end

app/models/admin.rb
class Admin < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins/books_controller.rb
class Admins::BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book Record successfully created."
      redirect_to :back
    else
      flash[:alert] = "Error while creating book record."
      redirect_to :back
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Book Record successfully created."
      redirect_to book_path(@book)
    else
      flash[:alert] = "Error while creating book record."
      redirect_to :back
    end
  end

  private

  def book_params
    params.require(:book).permit(
      :title, :author, :summary, :link_to_amazon_com, :link_to_amazon_in,
      :main_image_link, :youtube_audiobook_link, :youtube_animated_review_link
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def home

  end

  def user_home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/books/_form.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <div class="well">
    <%= form_for @book, url: (action_name == 'create' ? admins_books_path : admins_book_path(@book)) do |f| %>
      <fieldset>
        <legend>Book Record</legend>
      <div class="form-group col-sm-6">
        <label>Title</label>
        <%= f.text_field :title, class: "form-control"%>
      </div>
      <div class="form-group col-sm-6">
        <label>Author</label>
        <%= f.text_field :author, class: "form-control"%>
      </div>
      <div class="form-group col-sm-12">
        <label>Summary</label>
        <%= f.text_area :summary, class: "form-control"%>
      </div>
      <div class="form-group col-sm-12">
        <label>Link for amazon.com</label>
        <%= f.text_field :link_to_amazon_com, class: "form-control"%>
      </div>
      <div class="form-group col-sm-12">
        <label>Link for amazon.in</label>
        <%= f.text_field :link_to_amazon_in, class: "form-control"%>
      </div>
      <div class="form-group col-sm-12">
        <label>Main Image Link</label>
        <%= f.text_field :main_image_link, class: "form-control"%>
      </div>
      <div class="form-group col-sm-12">
        <label>Youtube Audibook Link</label>
        <%= f.text_field :youtube_audiobook_link, class: "form-control"%>
      </div>
      <div class="form-group col-sm-12">
        <label>Animated Review Youtube Link</label>
        <%= f.text_field :youtube_animated_review_link, class: "form-control"%>
      </div>
      <div class="form-group col-sm-12 text-center">
        <%= f.submit 'Save', class: "btn btn-success"%>
      </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/admins/books/edit.html.erb
<%= render 'form' %>

app/views/admins/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <center>
      <%= image_tag @book.main_image_link, width: 200, height: 300, class: 'm-t-30' %>
      <div class="br-wrapper br-theme-fontawesome-stars m-t-20">
        <%= select_tag :book_rating, options_for_select([1,2,3,4,5], selected: 3), id: 'book-rating' %>
        <small>rated 3.4 by 1000 users</small>
      </div>
    </center>
  </div>
  <div class="col-sm-6">
    <h2> <%= @book.title %></h2>
    <h4><small>by</small> <small class="text-primary"><%= @book.author%></small> </h4>
    <ul class="nav nav-tabs">
      <li class="active"><a href="#amazon-link" data-toggle="tab" aria-expanded="false">Amazon Link</a></li>
      <li class=""><a href="#audiobook" data-toggle="tab" aria-expanded="false">Audiobook</a></li>
      <li class=""><a href="#animated-review" data-toggle="tab" aria-expanded="true">Animated Review</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in text-center" id="amazon-link">
        <br/>
        <%= link_to "Buy from Amazon", @book.link_to_amazon_in, class: "btn btn-success" %>
      </div>
      <div class="tab-pane fade text-center" id="audiobook">
        <br/>
        <%= YouTubeAddy.youtube_embed_url(@book.youtube_audiobook_link,500,315).html_safe %>
      </div>
      <div class="tab-pane fade text-center" id="animated-review">
        <br/>
        <%= YouTubeAddy.youtube_embed_url(@book.youtube_animated_review_link,500,315).html_safe %>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-sm-12">
    <h4>Summary</h4>
    <p><%= @book.summary %></p>
  </div>
</div>
<hr>

app/views/dashboard/home.html.erb
<!-- Page Content -->

<!-- Image Slider Start -->
<div id="bootstrap-touch-slider" class="carousel bs-slider slide  control-round indicators-line" data-ride="carousel" data-pause="hover" data-interval="5000" >

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#bootstrap-touch-slider" data-slide-to="0" class="active"></li>
    <li data-target="#bootstrap-touch-slider" data-slide-to="1"></li>
    <li data-target="#bootstrap-touch-slider" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper For Slides -->
  <div class="carousel-inner" role="listbox">

    <!-- Third Slide -->
    <div class="item active">

      <!-- Slide Background -->
      <%= image_tag "book_image_1.jpg", class: 'slide-image'%>
      <div class="bs-slider-overlay"></div>

      <div class="container">
        <div class="row">
          <!-- Slide Text Layer -->
          <div class="slide-text slide_style_right">
            <h1 data-animation="animated zoomInRight">Bootstrap Carousel</h1>
            <p data-animation="animated fadeInLeft">Bootstrap carousel now touch enable slide.</p>
            <a href="http://bootstrapthemes.co/" target="_blank" class="btn btn-default" data-animation="animated fadeInLeft">select one</a>
            <a href="http://bootstrapthemes.co/" target="_blank"  class="btn btn-primary" data-animation="animated fadeInRight">select two</a>
          </div>
        </div>
      </div>
    </div>
    <!-- End of Slide -->

    <!-- Second Slide -->
    <div class="item">

      <!-- Slide Background -->
      <%= image_tag "book_image_2.jpg", class: 'slide-image'%>
      <div class="bs-slider-overlay"></div>
      <!-- Slide Text Layer -->
      <div class="slide-text slide_style_left">
        <h1 data-animation="animated flipInX">Best Books Ever.</h1>
        <p data-animation="animated lightSpeedIn">Make Bootstrap Better together.</p>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-default', data: { animation: 'animated fadeInUp' } %>
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary', data: { animation: 'animated fadeInDown' } %>
      </div>
    </div>
    <!-- End of Slide -->

    <!-- Third Slide -->
    <div class="item">

      <!-- Slide Background -->
      <%= image_tag "book_image_3.jpg", class: 'slide-image'%>
      <div class="bs-slider-overlay"></div>
      <!-- Slide Text Layer -->
      <div class="slide-text slide_style_left">
        <h1 data-animation="animated zoomInLeft">Beautiful Animations</h1>
        <p data-animation="animated fadeInRight">Lots of css3 Animations to make slide beautiful .</p>
        <a href="http://bootstrapthemes.co/" target="_blank" class="btn btn-default" data-animation="animated fadeInLeft">select one</a>
        <a href="http://bootstrapthemes.co/" target="_blank" class="btn btn-primary" data-animation="animated fadeInRight">select two</a>
      </div>
    </div>
    <!-- End of Slide -->


  </div><!-- End of Wrapper For Slides -->

  <!-- Left Control -->
  <a class="left carousel-control" href="#bootstrap-touch-slider" role="button" data-slide="prev">
    <span class="fa fa-angle-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>

  <!-- Right Control -->
  <a class="right carousel-control" href="#bootstrap-touch-slider" role="button" data-slide="next">
    <span class="fa fa-angle-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div> <!-- End  bootstrap-touch-slider Slider -->

<hr>

<!-- Title -->
<div class="row">
  <div class="col-lg-12">
    <h3>Latest Features</h3>
  </div>
</div>
<!-- /.row -->

<!-- Page Features -->
<div class="row text-center">

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="http://placehold.it/800x500" alt="">
      <div class="caption">
        <h3>Feature Label</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p>
        <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="http://placehold.it/800x500" alt="">
      <div class="caption">
        <h3>Feature Label</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p>
        <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="http://placehold.it/800x500" alt="">
      <div class="caption">
        <h3>Feature Label</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p>
        <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <img src="http://placehold.it/800x500" alt="">
      <div class="caption">
        <h3>Feature Label</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <p>
        <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
        </p>
      </div>
    </div>
  </div>

</div>
<!-- /.row -->

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Best Books Ever</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Recommended By <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? || admin_signed_in? %>
        <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </li>
        <% else %>
        <li> <%= link_to 'Sign Up', new_user_registration_path %> </li>
        <li> <%= link_to 'Sign In', new_user_session_path %> </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bestbooksever</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet" media="all">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <!-- Devise flash message -->
    <div class="container m-t-50">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>


      <%= yield %>

      <footer>
        <div class="row">
          <div class="col-lg-12">
            <hr>
            <p>Copyright &copy; Your Website 2014</p>
          </div>
        </div>
      </footer>
    </div>

    <!-- Footer -->
  </body>
</html>